#!/usr/bin/lua
local lfs = require "lfs"

--WARNING: This will delete files in your home directory and replace them with symlinks to the directory you call this from!

--[[
TODO:
    - autogenerate file list?
    - pre-run warning with y/n
    - figure out how to deal with directories that do and don't exist
--]]

local links = {
    ".bash_profile",
    ".bashrc",
    ".gitconfig",
    ".xintrc",
    ".Xresources",
    --
    ".config/user-dirs.dirs",
    ".config/awesome", --Note: see special handling below
    --
    ".atom/config.cson",
    ".atom/keymap.cson",
    ".atom/packages" --Note: see special handling below
}

local dirs = {
    ".atom",
    ".config"
}

function isLinked(f1, f2)
    if lfs.attributes(f1, "ino") == lfs.attributes(f2, "ino")
    and lfs.attributes(f1, "dev") == lfs.attributes(f2, "dev") then
        return true
    end
end

--Hacky check to see if this is being run from the right place
if lfs.touch("dotfiles-install") ~= true then
    print("Please run this file from it's directory, or I can't stop it from fucking things up.")
    return
end 

local home = os.getenv("HOME")
local dots = lfs.currentdir()

--Make sure our directories exist
for k,v in pairs(dirs) do
   if lfs.touch(home.."/"..v) ~= true then
       lfs.mkdir(home.."/"..v)
   end
end

--Special Handling for .atom/packages
if not isLinked(home.."/.atom/packages", dots.."/.atom/packages") then
    print("    Removing any existing atom packages; I hope you didn't want those!\n    ---")
    os.execute("rm -rf "..home.."/.atom/packages")
end

if not isLinked(home.."/.config/awesome", dots.."/.config/awesome") then
    print("    Removing your .config/awesome stuff; sorry!\n    ---")
    os.execute("rm -rf "..home.."/.config/awesome")
end

--Remove old congifs and replace with links; I hope you backed up!
for k,v in pairs(links) do
    if isLinked(home.."/"..v, dots.."/"..v) then
	print("    Leaving "..home.."/"..v.."; it's already linked.")
    else
        print("    Replacing "..home.."/"..v.." with a link.")
        lfs.chdir(dots)
        os.remove(home.."/"..v)
        lfs.chdir(home)
        lfs.link(dots.."/"..v, v, true)
    end
end

print("Okay, it's done. I hope it went well!")
