#! /bin/bash

bspc config split_ratio             0.5
bspc config window_gap              16
bspc config border_width            4
bspc config -m eDP1 normal_border_color     \#006060
bspc config -m eDP1 focused_border_color    \#008080
bspc config -m eDP1 presel_feedback_color   \#008080

bspc monitor eDP1 -d scratch work web game

#rules don't seem to be working :/
#perhaps I'll handle them with a lua script.

#bspc rule -a Chromium desktop=web
#bspc rule -a Steam desktop=game
#bspc rule -a Feh state=floating
#bspc rule -a Atom desktop=work
