#!/usr/bin/lua

os.execute([=[
bspc config split_ratio             0.618
bspc config window_gap              16
bspc config border_width            4
bspc config normal_border_color     \#005050
bspc config focused_border_color    \#008080
bspc config presel_feedback_color   \#007070

bspc monitor eDP1 -d scratch work web game
]=])

--[[
rules don't seem to be working :/
perhaps I'll handle them with a script.

bspc rule -a Chromium desktop=web
bspc rule -a Steam desktop=game
bspc rule -a Feh state=floating
bspc rule -a Atom desktop=work
--]]
